/** Contact card helpers for @japofc/baileys. */

const EOL = '\r\n';

const asText = (value) => value === undefined || value === null ? '' : String(value);

const cleanParam = (value, fallback = 'OTHER') => {
    const text = asText(value || fallback).trim();
    const safe = text.replace(/[^A-Za-z0-9_-]/g, '').toUpperCase();
    return safe || fallback;
};

const splitProperty = (line) => {
    const colon = line.indexOf(':');
    if (colon === -1) return null;
    const head = line.slice(0, colon);
    const value = line.slice(colon + 1);
    const [name, ...paramParts] = head.split(';');
    const params = new Map();

    for (const part of paramParts) {
        if (!part) continue;
        const eq = part.indexOf('=');
        const key = (eq === -1 ? 'TYPE' : part.slice(0, eq)).toUpperCase();
        const raw = eq === -1 ? part : part.slice(eq + 1);
        const values = raw.split(',').filter(Boolean);
        const list = params.get(key) ?? [];
        list.push(...values);
        params.set(key, list);
    }

    return { name: name.toUpperCase(), params, value };
};

const unfoldLines = (text) => {
    const out = [];
    for (const line of asText(text).replace(/\r\n/g, '\n').split('\n')) {
        if ((line.startsWith(' ') || line.startsWith('\t')) && out.length) {
            out[out.length - 1] += line.slice(1);
        }
        else {
            out.push(line);
        }
    }
    return out;
};

/** Escape a value for VCARD 3.0 text fields. */
export const escapeVCard = (s) => asText(s)
    .replace(/\\/g, '\\\\')
    .replace(/\n/g, '\\n')
    .replace(/;/g, '\\;')
    .replace(/,/g, '\\,');

/** Reverse escapeVCard(). Unknown escape sequences keep their escaped char. */
export const unescapeVCard = (s) => asText(s).replace(/\\(.)/g, (_, ch) => ch === 'n' || ch === 'N' ? '\n' : ch);

/** Keep digits and plus signs only; useful before writing TEL values. */
export const formatPhone = (p) => asText(p).replace(/[^\d+]/g, '');

const nameParts = (fullName) => {
    const parts = asText(fullName).trim().split(/\s+/).filter(Boolean);
    if (parts.length <= 1) return { first: '', last: parts[0] ?? '' };
    return { first: parts.slice(0, -1).join(' '), last: parts.at(-1) ?? '' };
};

/** Build a VCARD 3.0 string from structured contact data. */
export const generateVCard = (contact) => {
    const fullName = asText(contact.fullName || contact.displayName).trim();
    if (!fullName) throw new Error('Contact fullName is required');

    const { first, last } = nameParts(fullName);
    const lines = [
        'BEGIN:VCARD',
        'VERSION:3.0',
        `N:${escapeVCard(last)};${escapeVCard(first)};;;`,
        `FN:${escapeVCard(fullName)}`
    ];

    if (contact.organization) lines.push(`ORG:${escapeVCard(contact.organization)}`);
    if (contact.title) lines.push(`TITLE:${escapeVCard(contact.title)}`);

    for (const phone of contact.phones ?? []) {
        const number = formatPhone(phone.number);
        if (!number) continue;
        const type = cleanParam(phone.type, 'CELL');
        const label = phone.label ? `;X-ABLabel=${escapeVCard(phone.label)}` : '';
        lines.push(`TEL;type=${type};type=VOICE${label}:${number}`);
    }

    for (const email of contact.emails ?? []) {
        if (!email.email) continue;
        lines.push(`EMAIL;type=${cleanParam(email.type)}:${escapeVCard(email.email)}`);
    }

    for (const url of contact.urls ?? []) {
        if (!url.url) continue;
        lines.push(`URL;type=${cleanParam(url.type)}:${escapeVCard(url.url)}`);
    }

    for (const address of contact.addresses ?? []) {
        const fields = [
            '',
            '',
            address.street,
            address.city,
            address.state,
            address.postalCode,
            address.country
        ].map(escapeVCard);
        lines.push(`ADR;type=${cleanParam(address.type)}:${fields.join(';')}`);
    }

    if (contact.birthday) lines.push(`BDAY:${escapeVCard(contact.birthday)}`);
    if (contact.note) lines.push(`NOTE:${escapeVCard(contact.note)}`);

    lines.push('END:VCARD');
    return lines.join(EOL);
};

export const generateVCards = (contacts) => contacts.map(generateVCard).join(EOL);

/** Parse the common VCARD fields generated by generateVCard(). */
export const parseVCard = (vcard) => {
    const contact = {};

    for (const line of unfoldLines(vcard)) {
        const property = splitProperty(line);
        if (!property) continue;

        const { name, params, value } = property;
        const type = params.get('TYPE')?.find((entry) => entry.toUpperCase() !== 'VOICE')?.toUpperCase();

        if (name === 'FN') {
            contact.fullName = unescapeVCard(value);
        }
        else if (name === 'N' && !contact.fullName) {
            const [last = '', first = ''] = value.split(';').map(unescapeVCard);
            contact.fullName = [first, last].filter(Boolean).join(' ') || undefined;
        }
        else if (name === 'ORG') {
            contact.organization = unescapeVCard(value);
        }
        else if (name === 'TITLE') {
            contact.title = unescapeVCard(value);
        }
        else if (name === 'TEL') {
            contact.phones ??= [];
            const phone = { number: value, type: type || 'CELL' };
            const label = params.get('X-ABLABEL')?.[0];
            if (label) phone.label = unescapeVCard(label);
            contact.phones.push(phone);
        }
        else if (name === 'EMAIL') {
            contact.emails ??= [];
            contact.emails.push({ email: unescapeVCard(value), type: type || 'OTHER' });
        }
        else if (name === 'URL') {
            contact.urls ??= [];
            contact.urls.push({ url: unescapeVCard(value), type: type || 'OTHER' });
        }
        else if (name === 'ADR') {
            contact.addresses ??= [];
            const [, , street = '', city = '', state = '', postalCode = '', country = ''] = value.split(';').map(unescapeVCard);
            contact.addresses.push({ street, city, state, postalCode, country, type: type || 'OTHER' });
        }
        else if (name === 'BDAY') {
            contact.birthday = unescapeVCard(value);
        }
        else if (name === 'NOTE') {
            contact.note = unescapeVCard(value);
        }
    }

    return contact;
};

/** Ready-to-send `contacts` message content for a single contact. */
export const createContactCard = (contact) => ({
    contacts: {
        displayName: contact.displayName || contact.fullName,
        contacts: [{ vcard: generateVCard(contact) }]
    }
});

/** Ready-to-send `contacts` message content for multiple contacts. */
export const createContactCards = (contacts) => ({
    contacts: {
        displayName: contacts.length === 1 ? contacts[0]?.displayName || contacts[0]?.fullName || '' : `${contacts.length} Contacts`,
        contacts: contacts.map((contact) => ({ vcard: generateVCard(contact) }))
    }
});

export const quickContact = (name, phone, options = {}) => ({
    fullName: name,
    phones: [{ number: phone, type: 'CELL' }],
    organization: options.organization,
    emails: options.email ? [{ email: options.email, type: 'WORK' }] : undefined
});
